### PR TITLE
Added error handling for AADSTS90072 durin login callback

### LINKED ISSUE #22: No handling for error AADSTS90072
When restricting an application's access to you tenant, you get a POST error because the error is not handled correctly.

To replicate, set up an application with access to you tenant only, log into a tenant that does not have access and try to enter site.

Error:
```json
{
"error": "interaction_required",
"error_description": "AADSTS90072: User account '{EmailHidden}' from identity provider 'https://sts.windows.net/id/' does not exist in tenant 'tenant' and cannot access the application 'id'(app name) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account Trace ID: tenantid Correlation ID: coorid Timestamp: 2020-02-09 17:33:33Z",
"error_uri": "https://login.microsoftonline.com/error?code=90072"
}
```

How to fix; Add handling of AADSTS90072 error code to fail in middleware.
```php
            if($errorDescription == "AADSTS90072"){
                // Do appropriate response and offer logoff and login?
            }
```

### PR DESCRIPTION
**Pull request by Kvaksrud**

### CODE REVIEW

**Review by danieltjewett — CHANGES_REQUESTED** [review]
Thanks for contributing!  If this gets any bigger, we probably should break this out into it's own handler function.  But what we have for now is fine.

My only recommendation is could we make this an `else if`?

**Comment by JustinByrne** [comment]
As an alternative to an `else if` an array can be used to store the error codes with a HTTP status code and a message to go alongside each error. Adding to the array will allow for more error codes to be added quickly in the future. I am happy to add this as a PR to @Mycosis fork if you want.

```php
$azureErrors = [
    'AADSTS50105' => [
        'HTTP_CODE' => '403',
        'msg' => 'User is not authorised within Azure AD to access this application.',
    ],
    'AADSTS90072' => [
        'HTTP_CODE' => '403',
        'msg' => 'The logged on User is not in the allowed Tenant. Log in with a User in the allowed Tenant.',
    ],
];

if (array_key_exists($errorDescription, $azureErrors)) {
    return abort($azureErrors[$errorDescription]['HTTP_CODE'], $azureErrors[$errorDescription]['msg']);
}
```

**Comment by danieltjewett** [comment]
@JustinByrne Go for it :)

**Comment by danieltjewett** [comment]
Fixed in https://github.com/rootinc/laravel-azure-middleware/pull/32

**Pull request closed without merging**
